changed way to determine distro; changed output format to env-style.

diff --git a/scripts/info b/scripts/info
--- a/scripts/info
+++ b/scripts/info
@@ -2,34 +2,50 @@
 
 SHORT_DESCRIPTION="Output basic information about your host."
 
+whatDistro() {
+	if [ -f /etc/alpine-release ]; then
+		echo "alpine"
+		return 0
+	fi
+	if [ -f /etc/centos-release ]; then
+		echo "centos"
+		return 0
+	fi
+	if [ -f /etc/lsb-release ]; then
+		echo "ubuntu"
+		return 0
+	fi
+	if [ -f /etc/fedora-release ]; then
+		echo "fedora"
+		return 0
+	fi
+	if [ -f /etc/redhat-release ]; then
+		echo "rhel"
+		return 0
+	fi
+
+	return 1
+}
+
+
 # make sure we're able to retrieve the distro release id (e.g., alpine, centos, ubuntu) and version id.
-DISTRO="$(cat /etc/os-release 2>/dev/null | grep "^ID=" | cut -d '=' -f2 | tr -d '"')"
+DISTRO="$(whatDistro)"
+if [ $? -ne 0 ]; then
+	(>&2 echo "Could not determine Linux distro. Exiting...")
+	exit 1
+fi
 RELEASE="$(cat /etc/os-release 2>/dev/null | grep "VERSION_ID=" | cut -d "=" -f2 | tr -d '"')"
 CODENAME="$(cat /etc/*-release 2>/dev/null | grep "^DISTRIB_CODENAME=" | cut -d '=' -f2 | tr -d '"')"
 ARCH="$(uname -m)"
 
-# Try to get PFRAC components from older meta-data in /etc (for CentOS and RHEL)
-if [ -z "$DISTRO" ] || [ -z "$RELEASE" ] || [ -z "$ARCH" ]; then
-        if [ ! -z "$(cat /etc/*-release | grep ^CentOS)" ]; then
-                DISTRO="centos"
-                RELEASE="$(cat /etc/*-release | grep ^CentOS | head -n 1 | sed 's/.*release //' | awk '{print $1}')"
-        elif [ ! -z "$(cat /etc/*-release | grep ^Red)" ]; then
-                DISTRO=rhel
-                RELEASE="$(cat /etc/*-release | grep ^Red | head -n 1 | sed 's/.*release //' | awk '{print $1}')"
-        else
-                echo "Could not determine Linux distro. DISTRO='$DISTRO', RELEASE='$RELEASE', ARCH='$ARCH'. Exiting..." >&2
-                exit 1
-        fi
-fi
-
-echo "os"
-echo "=="
-echo "distro: $DISTRO"
-echo "release: $RELEASE"
-echo "codename: $CODENAME"
-echo "arch: $ARCH"
+echo "#OS"
+echo "#=="
+echo "DISTRO=$DISTRO"
+echo "RELEASE=$RELEASE"
+echo "CODENAME=$CODENAME"
+echo "ARCH=$ARCH"
 echo
-echo "host"
-echo "===="
-echo "whoami: $(whoami)"
-echo "hostname: $HOSTNAME"
+echo "#HOST"
+echo "#===="
+echo "WHOAMI=$(whoami)"
+echo "HOSTNAME=$HOSTNAME"
