create backup files for fedora.

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -119,6 +119,18 @@ rpm_install() {
 
 	curl https://repo.polyverse.io/config/rpm/7/key -o "/etc/pki/RPM-GPG-KEY-Polyverse"
 
+        # create a backup file
+        if [ ! -f "${FILE}.pvbak" ]; then
+                echo "Backing up .repo files to .repo.pvbak..."
+		for x in /etc/yum.repos.d/*.repo; do mv "$x" "${x}.pvbak"; done
+                if [ $? -ne 0 ]; then
+                        echo "Unable to create backup file. This is unexpected, so exiting..."
+                        exit 1
+                fi
+        else
+                echo "Backup files *.pvbak already exists, so we'll leave it alone."
+        fi
+
 	printf "$1" > $FILE
 
 	# check that the file was installed properly
