fixed wrong var names.

diff --git a/scripts/list-installed-elf b/scripts/list-installed-elf
--- a/scripts/list-installed-elf
+++ b/scripts/list-installed-elf
@@ -118,11 +118,11 @@ PLV_ARCH="$(uname -m)"
 
 # TO DO: hack since centos 6 doesn't have a proper /etc/os-release file.
 if [ ! -z "$(cat /etc/*-release | grep "CentOS" | grep "6.9")" ]; then
-	DISTRO=centos
-	RELEASE=6
+        PLV_DISTRO=centos
+        PLV_RELEASE=6
 else
-	echo "Could not determine Linux distro. DISTRO='$DISTRO', RELEASE='$RELEASE', ARCH='$ARCH'. Exiting..." >&2
-	exit 1
+        echo "Could not determine Linux distro. DISTRO='$PLV_DISTRO', RELEASE='$PLV_RELEASE', ARCH='$PLV_ARCH'. Exiting..." >&2
+        exit 1
 fi
 
 case $PLV_DISTRO in
