centos 6 hack.

diff --git a/scripts/list-installed-elf b/scripts/list-installed-elf
--- a/scripts/list-installed-elf
+++ b/scripts/list-installed-elf
@@ -116,6 +116,15 @@ PLV_DISTRO=$(cat /etc/os-release 2>/dev/null | grep "^ID=" | cut -d '=' -f2 | tr
 PLV_RELEASE=$(cat /etc/os-release 2>/dev/null | grep "VERSION_ID=" | cut -d "=" -f2 | tr -d '"')
 PLV_ARCH="$(uname -m)"
 
+# TO DO: hack since centos 6 doesn't have a proper /etc/os-release file.
+if [ ! -z "$(cat /etc/*-release | grep "CentOS" | grep "6.9")" ]; then
+	DISTRO=centos
+	RELEASE=6
+else
+	echo "Could not determine Linux distro. DISTRO='$DISTRO', RELEASE='$RELEASE', ARCH='$ARCH'. Exiting..." >&2
+	exit 1
+fi
+
 case $PLV_DISTRO in
 	alpine)
 		LIST_FUNC="apk_list"
